routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::any('captcha-test', function()
{
    if (Request::getMethod() == 'POST')
    {
        $rules = ['captcha' => 'required|captcha'];
        $validator = Validator::make(Input::all(), $rules);
        if ($validator->fails())
        {
            echo '<p style="color: #ff0000;">Incorrect!</p>';
        }
        else
        {
            echo '<p style="color: #00ff30;">Matched :)</p>';
        }
    }

    $form = '<form method="post" action="captcha-test">';
    $form .= '<input type="hidden" name="_token" value="' . csrf_token() . '">';
    $form .= '<p>' . captcha_img() . '</p>';
    $form .= '<p><input type="text" name="captcha"></p>';
    $form .= '<p><button type="submit" name="check">Check</button></p>';
    $form .= '</form>';
    return $form;
});
Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});
/********operators routes*************/
// Authentication Routes...
Route::get('operator/login', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
]);
Route::post('operator/login', [
    'as' => '',
    'uses' => 'Auth\LoginController@login'
]);
Route::post('operator/logout', [
    'as' => 'logout',
    'uses' => 'Auth\LoginController@logout'
]);


// Password Reset Routes...
Route::post('password/email', [
    'as' => 'password.email',
    'uses' => 'Auth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('password/reset', [
    'as' => 'password.request',
    'uses' => 'Auth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('password/reset', [
    'as' => '',
    'uses' => 'Auth\ResetPasswordController@reset'
]);
Route::get('password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'Auth\ResetPasswordController@showResetForm'
]);

// Registration Routes...
Route::get('operator/register', [
    'as' => 'register',
    'uses' => 'Auth\RegisterController@showRegistrationForm'
]);
Route::post('operator/register', [
    'as' => '',
    'uses' => 'Auth\RegisterController@register'
]);
Route::group(['prefix'=>'operator','as'=>'operator.'] ,function(){
    Route::get('/','OperatorController@operator_panel');
    Route::get('/conversation','ConversationController@index')->name('allconv');
    Route::get('/conversations','ConversationController@index_all');
    Route::get('/conversations/{id}','ConversationController@show_one');
    Route::get('/conversation/{id}','ConversationController@show');
    Route::post('recievemessage',['as'=>'recievemessage','uses'=>'MessageController@recievemessage']);
    Route::post('sendmessage',['as'=>'sendmessage','uses'=>'MessageController@sendmessage']);
    Route::post('disactive',['as'=>'disactive','uses'=>'ConversationController@DisactiveConversation']);
    Route::post('active',['as'=>'active','uses'=>'ConversationController@ActiveConversation']);
    Route::post('endconv',['as'=>'endconv','uses'=>'ConversationController@EndConversation']);
    Route::get('count',function(){
        $count= App\Conversation::ConversationCount();
        return view('vendor.adminlte.conversation.count',compact('count'));
    })->name('count');
});


Route::group(['domain'=>'company'],function (){
    //site index route
    Route::get('/', function (){
        return view('index_page');
    })->name('home');
    Route::get('/home', 'HomeController@home')->name('home2');
/*    Route::get('/exchange', 'HomeController@exchange')->name('exchange');*/
/*    Route::get('/product/{product}','ProductController@show')->name('product.show');*/

});

//admin route group
Route::group(['prefix' => 'admin', 'as' => 'admin.'], function()
{
    Route::get('/','AdminController@admin_panel')->name('admin');
    route::resource('admin','AdminController',['except'=>['destroy']]);
    Route::post('admin/socials',['as'=>'socials','uses'=>'HomeController@socials']);
    Route::post('admin/config',['as'=>'config','uses'=>'HomeController@config']);
   /* route::resource('seller','SellerController',['except'=>['destroy']]);
    Route::get('sellers/register',['as'=>'sellers.register','uses'=> 'SellerAuth\RegisterController@showRegistrationForm']);
    Route::post('sellers/register',['as'=>'sellers.register','uses'=> 'SellerAuth\RegisterController@register']);*/
    // Registration Routes...
    Route::get('/register',['as'=>'register','uses'=> 'AdminAuth\RegisterController@showRegistrationForm']);
    Route::post('/register',['as'=>'register','uses'=> 'AdminAuth\RegisterController@register']);
    //Login Routes...
    Route::get('/login',['as'=>'login','uses'=>'AdminAuth\LoginController@showLoginForm']);
    Route::post('/login',['as'=>'login','uses'=>'AdminAuth\LoginController@login']);
    Route::get('/logout',['as'=>'logout','uses'=>'AdminAuth\LoginController@logout']);
    /******company routes ***********/
    Route::resource('company', 'CompanyController', ['except' => ['destroy']]);
    Route::delete('company/{id}','CompanyController@destroy')->name('company.delete');
    Route::resource('operator', 'OperatorController', ['except' => ['destroy']]);
    Route::delete('operator/{id}','OperatorController@destroy')->name('operator.delete');
    Route::resource('department', 'DepartmentController', ['except' => ['destroy']]);
    Route::delete('department/{id}','DepartmentController@destroy')->name('department.delete');
    Route::post('admin/loadepartment','DepartmentController@load_department')->name('loadepartment');
    Route::post('admin/loadoperators','OperatorController@load_operator')->name('loadoperator');
});
//product website side routes index

/**
 * Module Routes image manager
 */
Route::get('image-manager/view/{id}/thumb', [
    'as' => 'showthumb',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@thumb'
]);

Route::get('image-manager/view/{id}/{width?}/{height?}/{canvas?}', [
    'as' => 'media',
    'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@full'
])->where('width', '[0-9]+')->where('height', '[0-9]+')->where('canvas', 'canvas');

Route::group(['middleware' => config('image-manager.middleware')], function() {

    Route::get('image-manager', [
        'as' => 'ImageManager',
        'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@index'
    ]);

    Route::post('upload-image', [
        'as' => 'ImageManagerUpload',
        'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@store'
    ]);

    Route::get('image-manager-images', [
        'as' => 'ImageManagerImages',
        'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@getImages'
    ]);

    Route::get('image-manager/delete/{id}', [
        'as' => 'ImageManagerDelete',
        'uses' => '\\Joselfonseca\\ImageManager\\Controllers\\ImageManagerController@delete'
    ]);
});

////////add comment controller
/*Route::resource('comment','CommentController',['except'=>'show','destroy']);*/


Route::group(['prefix' => 'company', 'as' => 'company.'], function() {
        Route::get('/', 'CompanyController@Company_panel')->name('Company');
    Route::get('/register', ['as' => 'register', 'uses' => 'CompanyAuth\RegisterController@showRegistrationForm']);
    Route::post('/register', ['as' => 'register', 'uses' => 'CompanyAuth\RegisterController@register']);
    Route::get('/login', ['as' => 'login', 'uses' => 'CompanyAuth\LoginController@showLoginForm']);
    Route::post('/login', ['as' => 'login', 'uses' => 'CompanyAuth\LoginController@login']);
    Route::get('/logout', ['as' => 'logout', 'uses' => 'CompanyAuth\LoginController@logout']);
});





/********operators routes*************/
// Authentication Routes...
/*Route::get('company/login', [
    'as' => 'login',
    'uses' => 'CompanyAuth\LoginController@showLoginForm'
]);
Route::post('company/login', [
    'as' => '',
    'uses' => 'CompanyAuth\LoginController@login'
]);
Route::post('company/logout', [
    'as' => 'logout',
    'uses' => 'CompanyAuth\LoginController@logout'
]);

// Password Reset Routes...
Route::post('company/password/email', [
    'as' => 'password.email',
    'uses' => 'CompanyAuth\ForgotPasswordController@sendResetLinkEmail'
]);
Route::get('company/password/reset', [
    'as' => 'password.request',
    'uses' => 'CompanyAuth\ForgotPasswordController@showLinkRequestForm'
]);
Route::post('company/password/reset', [
    'as' => '',
    'uses' => 'CompanyAuth\ResetPasswordController@reset'
]);
Route::get('company/password/reset/{token}', [
    'as' => 'password.reset',
    'uses' => 'CompanyAuth\ResetPasswordController@showResetForm'
]);

// Registration Routes...
Route::get('company/register', [
    'as' => 'register',
    'uses' => 'CompanyAuth\RegisterController@showRegistrationForm'
]);
Route::post('company/register', [
    'as' => '',
    'uses' => 'CompanyAuth\RegisterController@register'
]);
Route::group(['prefix'=>'company','as'=>'company.'] ,function(){
    Route::get('/', 'CompanyController@Company_panel')->name('Company');
});*/

// Media-Manager
ctf0\MediaManager\MediaRoutes::routes();

/*
//Clear Config cache:
Route::get('/config-cache', function() {
    $exitCode = Artisan::call('config:cache');
    return '<h1>Clear Config cleared</h1>';
});


//Route cache:
Route::get('/route-cache', function() {
    $exitCode = Artisan::call('route:cache');
    return '<h1>Routes cached</h1>';
});

//Clear Route cache:
Route::get('/route-clear', function() {
    $exitCode = Artisan::call('route:clear');
    return '<h1>Route cache cleared</h1>';
});

//Clear View cache:

app/Operator.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Company;
class Operator extends Authenticatable
{
    use Notifiable;
    /*public  $birth_day_p;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','email','password','company_id','username'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
    public function departments()
    {
        return $this->belongsToMany(Department::class,'department_operators');
    }

 /*   public function getCountAttribute()
    {
        return Department::where([['product_id',$this->id],['status',1]])->avg('rating');
    }
*/


}

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;
use App\Company;
use App\Conversation;
use App\Message;
use App\Operator;
use Illuminate\Http\Request;
use App\Department;

class OperatorController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin')->only(['index','create','store','index','edit','update','destroy','load_operator']);
        $this->middleware('auth')->only('operator_panel');
    }

    public function operator_panel()
    {
        $departments = \Auth::user()->departments()->get();
        $operator_id = \Auth::user()->id;
        $conversation = Conversation::where('operator_id', $operator_id)->get();
        if ($conversation != null){
            foreach ($conversation as $conv) {
                $messages[] = Message::where([['type', 2], ['conversation_token', $conv->token]]);
            }
    }
        $loader[]=null;
        $loader['department_count']=count($departments);
        $loader['activeconv_count']=Conversation::ConversationCount();
        if(/*$messages!='' || $messages!=null || */isset($messages)) {
            $loader['messages_count'] = count($messages);
        }else{
            $loader['messages_count'] = 0;
        }
        $loader['conv_count']=count($conversation);
        return view('vendor.adminlte.home',compact('loader','conversation'));
    }


    public function show()
    {
    }
    public function create(Operator $operator)
    {
        $departments=Department::all();
        $companies=Company::all();
        return view('admin.operator.operator_add',compact('operator','companies','departments'));

    }
    public function store(Request $request,Operator $operator)
    {
        $this->validate($request,[
            'name'=>'required',
            'username'=>'required|min:3|unique:operators',
            'email'=>'required|email',
            'password' => 'required|min:3|confirmed',
            'password_confirmation' => 'required|min:3'
        ]);

        $operator=$operator->create([
            'name'=>$request->name,
            'email'=>$request->email,
            'username'=>$request->username,
            'password'=>bcrypt($request->password),
            'company_id'=>$request->company
        ]);
        $operator->departments()->attach($request->department);
        return redirect('admin/operator');
    }

    public function index(){
        $operators =Operator::all();
        return view('admin.operator.operator_show',compact('operators'));
    }
    public function edit(Operator $operator){
        $companies=Company::all();
        return view('admin.operator.operator_edit',compact('operator','companies'));
    }
    public function update(Request $request,Operator $operator)
    {
        $this->validate($request,[
           'name'=>'required',
           'username'=>'required|unique:operators,username,'.$operator->id,
            'email'=>'email',
            'company'=>'required|numeric'
        ]);
        $operator->update([
            'name'=>$request->name,
            'email'=>$request->email,
            'username'=>$request->username,
            'password'=>bcrypt($request->password),
            'company_id'=>$request->company
        ]);
        $operator->departments()->sync($request->department);
        return redirect('admin/operator');
    }

    public function destroy(Request $request)
    {
        Operator::find($request->id)->delete();
        return redirect('admin/operator');

    }

    public function load_operator(Request $request)
    {
        if($request->ajax()){
            $operators=Operator::where('company_id',$request->id)->get();
            $data = view('admin.operator.ajax_options',compact('operators'))->render();
            return response()->json(['options' => $data]);
        }
    }

}

resources/views/admin/operator/ajax_options.blade.php
@if(!empty($operators))
    @foreach($operators as $operator)
        <option value="{{ $operator->id }}">{{ $operator->name }}</option>
    @endforeach
@endif

resources/views/admin/operator/operator_add.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title')
    {{ trans('adminlte_lang::message.home') }}
@endsection
@section('contentheader_title','Add Operator')

@section('contentheader_description')
    adding opretors
@endsection
@section('main_page','Oprators')

@section('here_page','Add Oprators')

@section('main-content')
    <div class="container-fluid spark-screen">
        <section class="content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-plus "></i>ADD operator</h3>
                </div>
                <div class="panel-body">
                    <form action="{{route('admin.operator.store',$operator)}}" class="form-horizontal" method="post" enctype="multipart/form-data" id="form-category">
                        {{csrf_field()}}
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger alert-dismissible"> {!! $error !!}</div>
                        @endforeach
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="name">name</label>
                            <div class="col-sm-6">
                                <input id="name" name="name" value="{{old('name')}}" placeholder="name "  class="form-control" type="text">

                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="email">email</label>
                            <div class="col-sm-6">
                                <input id="name" name="email" value="{{old('email')}}" placeholder="email "  class="form-control" type="email">

                            </div>
                        </div>


                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">username</label>
                            <div class="col-sm-6">
                                <input id="name" name="username" value="{{old('username')}}" placeholder="username "  class="form-control" type="text">

                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">password</label>
                            <div class="col-sm-6">
                                <input id="name" name="password" value="" placeholder="password "  class="form-control" type="password">

                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">password confirmation</label>
                            <div class="col-sm-6">
                                <input id="name" name="password_confirmation"  class="form-control" type="password">
                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">company</label>
                            <div class="col-sm-6">
<select name="company" id="company-list" class="form-control">
    <option value="0">select your favourite company</option>
@foreach($companies as $company)
    <option value="{{$company->id}}">{{$company->name}}</option>
    @endforeach
</select>
                            </div>
                        </div>
                      {{--  <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">company</label>
                            <div class="col-sm-6">
                                <select name="department[]" class="form-control" multiple="multiple">
                                    @foreach($departments as $department)
                                        <option value="{{$department->id}}">{{$department->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>--}}
                          <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">Department</label>
                            <div class="col-sm-6">
                                <select name="department[]" class="form-control" id="result" multiple="multiple">
                                </select>

                            </div>
                        </div>

                        <button class="btn btn-success" style="width: 100%">Add</button>

                    </form>
                </div>
            </div>

        </section>

    </div>
@endsection
@section('inline_script')
<script>
    $("#company-list").change(function(){
        //alert('aasd');
        var id = $(this).val();
        var csrf_token=$('meta[name="csrf-token"]').attr('content');
        $.ajax({url: "{{route('admin.loadepartment')}}",method:'post',data: {id:id,_token:csrf_token} ,success: function(data){
                $('#result').html('');
                $('#result').html(data.options);

            }
        });
    });


</script>

    @endsection

resources/views/admin/operator/operator_edit.blade.php
@extends('admin.layouts.app')

@section('htmlheader_title')
    Edit Oprators
@endsection
@section('contentheader_title','Oprators')

@section('contentheader_description','Edit Operators')
@section('main_page','Operators')

@section('here_page','Edit Operators')


@section('main-content')
    <div class="container-fluid spark-screen">
        <section class="content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><i class="fa fa-plus "></i>Edit operator</h3>
                </div>
                <div class="panel-body">

                    <form action="{{route('admin.operator.update',$operator)}}" class="form-horizontal" method="post" enctype="multipart/form-data" id="form-category">
                        {{csrf_field()}}
                        {{method_field('PATCH')}}
                        @foreach($errors->all() as $error)
                            <div class="alert alert-danger">{{$error}}</div>
                            @endforeach
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="name">name</label>
                            <div class="col-sm-6">
                                <input id="name" name="name" value="{{$operator->name}}" placeholder="name"  class="form-control" type="text">

                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="email">email</label>
                            <div class="col-sm-6">
                                <input id="name" name="email" value="{{$operator->email}}" placeholder="email"  class="form-control" type="email">

                            </div>
                        </div>
                        <div class="pull-right">
                            <div class="dep-box">
                                <div class="head_department">User Current Departments</div>
                                <ul class="correct-dep">
                                    @foreach($operator->departments as $department)
                                        <li class="itemsha">{{$department->name}}</li>
                                    @endforeach

                                </ul>
                            </div>
                        </div>


                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">username</label>
                            <div class="col-sm-6">
                                <input id="name" name="username" value="{{$operator->username}}" placeholder="any username"  class="form-control" type="text">

                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">password</label>
                            <div class="col-sm-6">
                                <input id="name" name="password" value="" placeholder="password"  class="form-control" type="password">

                            </div>
                        </div>
                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">company</label>
                            <div class="col-sm-6">
                                <select name="company" class="form-control" id="company">
                                    <option value="0">select new company</option>
                                    @foreach($companies as $company)
                                        <option @if($operator->Company->id==$company->id) {{'selected'}}  @endif value="{{$company->id}}">{{$company->name}}</option>
                                    @endforeach
                                </select>
                                <span class="help-block">First of all change the company to load its departments</span>
                            </div>
                        </div>

                        <div class="form-group required">
                            <label class="col-sm-2 control-label" for="tel">Departments</label>
                            <div class="col-sm-6">
                                <select name="department[]" id="result" class="form-control" multiple="multiple">
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-success" style="width: 100%">Edit</button>

                    </form>
                </div>
            </div>

        </section>

    </div>
@endsection

@section('inline_script')
    <script>
        $("#company").change(function(){
            var id = $(this).val();
            var csrf_token=$('meta[name="csrf-token"]').attr('content');
            $.ajax({url: "{{route('admin.loadepartment')}}",method:'post',data: {id:id,_token:csrf_token} ,success: function(data){
                    $('#result').html('');
                    $('#result').html(data.options);

                }
            });
        });


    </script>

@endsection

@section('iternal_css')
    <style>
        .head_department {
            background: #ff00004d;
            padding: 5px;
            border-radius: 5px;
        }

        .itemsha {
            list-style: symbols;
        }
    </style>

    @endsection

resources/views/admin/operator/operator_show.blade.php
@extends('admin.layouts.app')
@section('htmlheader_title')
    Operators
@endsection
@section('contentheader_title','Operators')

@section('contentheader_description','all Operators')
@section('main_page','Operators')

@section('here_page','All Operators')

@section('main-content')
    <div class="container-fluid spark-screen">
        <div class="row">
            <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Operators</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <a href="{{route('admin.operator.create')}}">
                        <button type="button" style="margin-bottom:1%;" class="center-block btn btn-success">Add new Operator</button>                    </a>
                    </a>
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>name</th>
                            <th>username</th>
                            <th>email</th>
                            <th>company</th>
                            <th>Departments</th>
                            <th>edit</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($operators as $operator)
                        <tr>
                            <td>{{$operator->name}}</td>
                            <td>{{$operator->username}}</td>
                            <td>{{$operator->email}}</td>
                            <td>{{$operator->Company->name}}</td>
                            <td>
                                <ul>
                                @foreach($operator->departments as $department)
                                    <li>{{$department->name}}</li>
                                @endforeach
                                </ul>
                            </td>
                            <td>
{{--
                                <button type="button" href="" class="btn btn-success">Show</button>
--}}
                             <a href="{{route('admin.operator.edit',$operator)}}"> <button type="button" class="btn btn-primary">Edit</button></a>
                                <form action="{{ url('admin/operator', ['id' => $operator->id]) }}" method="post">
                                    <input type="hidden" name="_method" value="delete" />
                                    {{csrf_field()}}
                                    <button type="submit" href="" class="btn btn-danger">DELETE</button>
                                </form>
                            </td>

                        </tr>
                          @endforeach
                        </tbody>
                        {{--<tfoot>
                        <tr>
                            <th>Rendering engine</th>
                            <th>Browser</th>
                            <th>Platform(s)</th>
                            <th>Engine version</th>
                            <th>CSS grade</th>
                        </tr>
                        </tfoot>--}}
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->

        </div>
    </div>
@endsection
@section('iternal_css')
    <link rel="stylesheet" href="{{asset('css/dataTables.bootstrap.min.css')}}">
@endsection
@section('inline_script')
    <script type="text/javascript" src="{{asset('js/jquery.dataTables.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(function () {
            $('#example1').DataTable();
            /*   $('#example1').DataTable({
                   'paging'      : true,
                   'lengthChange': false,
                   'searching'   : true,
                   'ordering'    : true,
                   'info'        : true,
                   'autoWidth'   : false
               });*/
        })
    </script>
@endsection